---
# Add additional stages in the order of execution here, and then under the job:include: key
stages:
  - "lint"
  - "test"
  - name: "deploy-github"
    if: "tag IS present"
  - name: "deploy-pypi"
    if: "tag IS present"

language: "python"

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

# Script & Before Script for test stage
before_script:
  - "pip install invoke poetry toml"
  - "poetry install"
script:
  - "invoke pytest --local"

jobs:
  include:
    - stage: "lint"
      env:
        - "INVOKE_LOCAL=True"
      before_script:
        - "pip install invoke poetry toml"
        - "poetry install --no-interaction --no-ansi --no-root"
      script:
        - "invoke black"
        - "invoke bandit"
        - "invoke pydocstyle"
        - "invoke mypy"
        - "invoke flake8"
        - "invoke yamllint"
        - "invoke pylint"
      python: 3.7

    - stage: "deploy-github"
      before_script:
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry build"
      deploy:
        provider: "releases"
        api_key: "$GITHUB_AUTH_TOKEN"
        file_glob: true
        file: "dist/*"
        skip_cleanup: true
        "on":
          all_branches: true

    - stage: "deploy-pypi"
      before_script:
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry config pypi-token.pypi $PYPI_TOKEN"
        - "poetry publish --build"
